# Generated by Django 4.0 on 2022-03-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.IntegerField()),
                ('nome', models.CharField(max_length=100)),
                ('setor', models.CharField(max_length=50)),
                ('funcao', models.CharField(max_length=50)),
                ('mobile', models.IntegerField()),
                ('caf', models.CharField(max_length=50)),
                ('armario', models.IntegerField()),
                ('chave', models.IntegerField()),
            ],
        ),
    ]
